# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /root/fpgaminer-aws

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /root/fpgaminer-aws

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /root/fpgaminer-aws/CMakeFiles /root/fpgaminer-aws/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /root/fpgaminer-aws/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named fpga_miner

# Build rule for target.
fpga_miner: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fpga_miner
.PHONY : fpga_miner

# fast build rule for target.
fpga_miner/fast:
	$(MAKE) -f CMakeFiles/fpga_miner.dir/build.make CMakeFiles/fpga_miner.dir/build
.PHONY : fpga_miner/fast

#=============================================================================
# Target rules for targets named jansson

# Build rule for target.
jansson: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 jansson
.PHONY : jansson

# fast build rule for target.
jansson/fast:
	$(MAKE) -f compat/jansson/CMakeFiles/jansson.dir/build.make compat/jansson/CMakeFiles/jansson.dir/build
.PHONY : jansson/fast

algo/blake256-8.o: algo/blake256-8.c.o
.PHONY : algo/blake256-8.o

# target to build an object file
algo/blake256-8.c.o:
	$(MAKE) -f CMakeFiles/fpga_miner.dir/build.make CMakeFiles/fpga_miner.dir/algo/blake256-8.c.o
.PHONY : algo/blake256-8.c.o

algo/blake256-8.i: algo/blake256-8.c.i
.PHONY : algo/blake256-8.i

# target to preprocess a source file
algo/blake256-8.c.i:
	$(MAKE) -f CMakeFiles/fpga_miner.dir/build.make CMakeFiles/fpga_miner.dir/algo/blake256-8.c.i
.PHONY : algo/blake256-8.c.i

algo/blake256-8.s: algo/blake256-8.c.s
.PHONY : algo/blake256-8.s

# target to generate assembly for a file
algo/blake256-8.c.s:
	$(MAKE) -f CMakeFiles/fpga_miner.dir/build.make CMakeFiles/fpga_miner.dir/algo/blake256-8.c.s
.PHONY : algo/blake256-8.c.s

algo/blake2s.o: algo/blake2s.c.o
.PHONY : algo/blake2s.o

# target to build an object file
algo/blake2s.c.o:
	$(MAKE) -f CMakeFiles/fpga_miner.dir/build.make CMakeFiles/fpga_miner.dir/algo/blake2s.c.o
.PHONY : algo/blake2s.c.o

algo/blake2s.i: algo/blake2s.c.i
.PHONY : algo/blake2s.i

# target to preprocess a source file
algo/blake2s.c.i:
	$(MAKE) -f CMakeFiles/fpga_miner.dir/build.make CMakeFiles/fpga_miner.dir/algo/blake2s.c.i
.PHONY : algo/blake2s.c.i

algo/blake2s.s: algo/blake2s.c.s
.PHONY : algo/blake2s.s

# target to generate assembly for a file
algo/blake2s.c.s:
	$(MAKE) -f CMakeFiles/fpga_miner.dir/build.make CMakeFiles/fpga_miner.dir/algo/blake2s.c.s
.PHONY : algo/blake2s.c.s

algo/groestl.o: algo/groestl.c.o
.PHONY : algo/groestl.o

# target to build an object file
algo/groestl.c.o:
	$(MAKE) -f CMakeFiles/fpga_miner.dir/build.make CMakeFiles/fpga_miner.dir/algo/groestl.c.o
.PHONY : algo/groestl.c.o

algo/groestl.i: algo/groestl.c.i
.PHONY : algo/groestl.i

# target to preprocess a source file
algo/groestl.c.i:
	$(MAKE) -f CMakeFiles/fpga_miner.dir/build.make CMakeFiles/fpga_miner.dir/algo/groestl.c.i
.PHONY : algo/groestl.c.i

algo/groestl.s: algo/groestl.c.s
.PHONY : algo/groestl.s

# target to generate assembly for a file
algo/groestl.c.s:
	$(MAKE) -f CMakeFiles/fpga_miner.dir/build.make CMakeFiles/fpga_miner.dir/algo/groestl.c.s
.PHONY : algo/groestl.c.s

algo/keccak256.o: algo/keccak256.c.o
.PHONY : algo/keccak256.o

# target to build an object file
algo/keccak256.c.o:
	$(MAKE) -f CMakeFiles/fpga_miner.dir/build.make CMakeFiles/fpga_miner.dir/algo/keccak256.c.o
.PHONY : algo/keccak256.c.o

algo/keccak256.i: algo/keccak256.c.i
.PHONY : algo/keccak256.i

# target to preprocess a source file
algo/keccak256.c.i:
	$(MAKE) -f CMakeFiles/fpga_miner.dir/build.make CMakeFiles/fpga_miner.dir/algo/keccak256.c.i
.PHONY : algo/keccak256.c.i

algo/keccak256.s: algo/keccak256.c.s
.PHONY : algo/keccak256.s

# target to generate assembly for a file
algo/keccak256.c.s:
	$(MAKE) -f CMakeFiles/fpga_miner.dir/build.make CMakeFiles/fpga_miner.dir/algo/keccak256.c.s
.PHONY : algo/keccak256.c.s

algo/keccak512.o: algo/keccak512.c.o
.PHONY : algo/keccak512.o

# target to build an object file
algo/keccak512.c.o:
	$(MAKE) -f CMakeFiles/fpga_miner.dir/build.make CMakeFiles/fpga_miner.dir/algo/keccak512.c.o
.PHONY : algo/keccak512.c.o

algo/keccak512.i: algo/keccak512.c.i
.PHONY : algo/keccak512.i

# target to preprocess a source file
algo/keccak512.c.i:
	$(MAKE) -f CMakeFiles/fpga_miner.dir/build.make CMakeFiles/fpga_miner.dir/algo/keccak512.c.i
.PHONY : algo/keccak512.c.i

algo/keccak512.s: algo/keccak512.c.s
.PHONY : algo/keccak512.s

# target to generate assembly for a file
algo/keccak512.c.s:
	$(MAKE) -f CMakeFiles/fpga_miner.dir/build.make CMakeFiles/fpga_miner.dir/algo/keccak512.c.s
.PHONY : algo/keccak512.c.s

algo/lyra2.o: algo/lyra2.c.o
.PHONY : algo/lyra2.o

# target to build an object file
algo/lyra2.c.o:
	$(MAKE) -f CMakeFiles/fpga_miner.dir/build.make CMakeFiles/fpga_miner.dir/algo/lyra2.c.o
.PHONY : algo/lyra2.c.o

algo/lyra2.i: algo/lyra2.c.i
.PHONY : algo/lyra2.i

# target to preprocess a source file
algo/lyra2.c.i:
	$(MAKE) -f CMakeFiles/fpga_miner.dir/build.make CMakeFiles/fpga_miner.dir/algo/lyra2.c.i
.PHONY : algo/lyra2.c.i

algo/lyra2.s: algo/lyra2.c.s
.PHONY : algo/lyra2.s

# target to generate assembly for a file
algo/lyra2.c.s:
	$(MAKE) -f CMakeFiles/fpga_miner.dir/build.make CMakeFiles/fpga_miner.dir/algo/lyra2.c.s
.PHONY : algo/lyra2.c.s

algo/lyra2re.o: algo/lyra2re.c.o
.PHONY : algo/lyra2re.o

# target to build an object file
algo/lyra2re.c.o:
	$(MAKE) -f CMakeFiles/fpga_miner.dir/build.make CMakeFiles/fpga_miner.dir/algo/lyra2re.c.o
.PHONY : algo/lyra2re.c.o

algo/lyra2re.i: algo/lyra2re.c.i
.PHONY : algo/lyra2re.i

# target to preprocess a source file
algo/lyra2re.c.i:
	$(MAKE) -f CMakeFiles/fpga_miner.dir/build.make CMakeFiles/fpga_miner.dir/algo/lyra2re.c.i
.PHONY : algo/lyra2re.c.i

algo/lyra2re.s: algo/lyra2re.c.s
.PHONY : algo/lyra2re.s

# target to generate assembly for a file
algo/lyra2re.c.s:
	$(MAKE) -f CMakeFiles/fpga_miner.dir/build.make CMakeFiles/fpga_miner.dir/algo/lyra2re.c.s
.PHONY : algo/lyra2re.c.s

algo/myr-groestl.o: algo/myr-groestl.c.o
.PHONY : algo/myr-groestl.o

# target to build an object file
algo/myr-groestl.c.o:
	$(MAKE) -f CMakeFiles/fpga_miner.dir/build.make CMakeFiles/fpga_miner.dir/algo/myr-groestl.c.o
.PHONY : algo/myr-groestl.c.o

algo/myr-groestl.i: algo/myr-groestl.c.i
.PHONY : algo/myr-groestl.i

# target to preprocess a source file
algo/myr-groestl.c.i:
	$(MAKE) -f CMakeFiles/fpga_miner.dir/build.make CMakeFiles/fpga_miner.dir/algo/myr-groestl.c.i
.PHONY : algo/myr-groestl.c.i

algo/myr-groestl.s: algo/myr-groestl.c.s
.PHONY : algo/myr-groestl.s

# target to generate assembly for a file
algo/myr-groestl.c.s:
	$(MAKE) -f CMakeFiles/fpga_miner.dir/build.make CMakeFiles/fpga_miner.dir/algo/myr-groestl.c.s
.PHONY : algo/myr-groestl.c.s

algo/nist5.o: algo/nist5.c.o
.PHONY : algo/nist5.o

# target to build an object file
algo/nist5.c.o:
	$(MAKE) -f CMakeFiles/fpga_miner.dir/build.make CMakeFiles/fpga_miner.dir/algo/nist5.c.o
.PHONY : algo/nist5.c.o

algo/nist5.i: algo/nist5.c.i
.PHONY : algo/nist5.i

# target to preprocess a source file
algo/nist5.c.i:
	$(MAKE) -f CMakeFiles/fpga_miner.dir/build.make CMakeFiles/fpga_miner.dir/algo/nist5.c.i
.PHONY : algo/nist5.c.i

algo/nist5.s: algo/nist5.c.s
.PHONY : algo/nist5.s

# target to generate assembly for a file
algo/nist5.c.s:
	$(MAKE) -f CMakeFiles/fpga_miner.dir/build.make CMakeFiles/fpga_miner.dir/algo/nist5.c.s
.PHONY : algo/nist5.c.s

algo/sha2.o: algo/sha2.c.o
.PHONY : algo/sha2.o

# target to build an object file
algo/sha2.c.o:
	$(MAKE) -f CMakeFiles/fpga_miner.dir/build.make CMakeFiles/fpga_miner.dir/algo/sha2.c.o
.PHONY : algo/sha2.c.o

algo/sha2.i: algo/sha2.c.i
.PHONY : algo/sha2.i

# target to preprocess a source file
algo/sha2.c.i:
	$(MAKE) -f CMakeFiles/fpga_miner.dir/build.make CMakeFiles/fpga_miner.dir/algo/sha2.c.i
.PHONY : algo/sha2.c.i

algo/sha2.s: algo/sha2.c.s
.PHONY : algo/sha2.s

# target to generate assembly for a file
algo/sha2.c.s:
	$(MAKE) -f CMakeFiles/fpga_miner.dir/build.make CMakeFiles/fpga_miner.dir/algo/sha2.c.s
.PHONY : algo/sha2.c.s

algo/sph_blake.o: algo/sph_blake.c.o
.PHONY : algo/sph_blake.o

# target to build an object file
algo/sph_blake.c.o:
	$(MAKE) -f CMakeFiles/fpga_miner.dir/build.make CMakeFiles/fpga_miner.dir/algo/sph_blake.c.o
.PHONY : algo/sph_blake.c.o

algo/sph_blake.i: algo/sph_blake.c.i
.PHONY : algo/sph_blake.i

# target to preprocess a source file
algo/sph_blake.c.i:
	$(MAKE) -f CMakeFiles/fpga_miner.dir/build.make CMakeFiles/fpga_miner.dir/algo/sph_blake.c.i
.PHONY : algo/sph_blake.c.i

algo/sph_blake.s: algo/sph_blake.c.s
.PHONY : algo/sph_blake.s

# target to generate assembly for a file
algo/sph_blake.c.s:
	$(MAKE) -f CMakeFiles/fpga_miner.dir/build.make CMakeFiles/fpga_miner.dir/algo/sph_blake.c.s
.PHONY : algo/sph_blake.c.s

algo/sph_blake2s.o: algo/sph_blake2s.c.o
.PHONY : algo/sph_blake2s.o

# target to build an object file
algo/sph_blake2s.c.o:
	$(MAKE) -f CMakeFiles/fpga_miner.dir/build.make CMakeFiles/fpga_miner.dir/algo/sph_blake2s.c.o
.PHONY : algo/sph_blake2s.c.o

algo/sph_blake2s.i: algo/sph_blake2s.c.i
.PHONY : algo/sph_blake2s.i

# target to preprocess a source file
algo/sph_blake2s.c.i:
	$(MAKE) -f CMakeFiles/fpga_miner.dir/build.make CMakeFiles/fpga_miner.dir/algo/sph_blake2s.c.i
.PHONY : algo/sph_blake2s.c.i

algo/sph_blake2s.s: algo/sph_blake2s.c.s
.PHONY : algo/sph_blake2s.s

# target to generate assembly for a file
algo/sph_blake2s.c.s:
	$(MAKE) -f CMakeFiles/fpga_miner.dir/build.make CMakeFiles/fpga_miner.dir/algo/sph_blake2s.c.s
.PHONY : algo/sph_blake2s.c.s

algo/sph_bmw.o: algo/sph_bmw.c.o
.PHONY : algo/sph_bmw.o

# target to build an object file
algo/sph_bmw.c.o:
	$(MAKE) -f CMakeFiles/fpga_miner.dir/build.make CMakeFiles/fpga_miner.dir/algo/sph_bmw.c.o
.PHONY : algo/sph_bmw.c.o

algo/sph_bmw.i: algo/sph_bmw.c.i
.PHONY : algo/sph_bmw.i

# target to preprocess a source file
algo/sph_bmw.c.i:
	$(MAKE) -f CMakeFiles/fpga_miner.dir/build.make CMakeFiles/fpga_miner.dir/algo/sph_bmw.c.i
.PHONY : algo/sph_bmw.c.i

algo/sph_bmw.s: algo/sph_bmw.c.s
.PHONY : algo/sph_bmw.s

# target to generate assembly for a file
algo/sph_bmw.c.s:
	$(MAKE) -f CMakeFiles/fpga_miner.dir/build.make CMakeFiles/fpga_miner.dir/algo/sph_bmw.c.s
.PHONY : algo/sph_bmw.c.s

algo/sph_cubehash.o: algo/sph_cubehash.c.o
.PHONY : algo/sph_cubehash.o

# target to build an object file
algo/sph_cubehash.c.o:
	$(MAKE) -f CMakeFiles/fpga_miner.dir/build.make CMakeFiles/fpga_miner.dir/algo/sph_cubehash.c.o
.PHONY : algo/sph_cubehash.c.o

algo/sph_cubehash.i: algo/sph_cubehash.c.i
.PHONY : algo/sph_cubehash.i

# target to preprocess a source file
algo/sph_cubehash.c.i:
	$(MAKE) -f CMakeFiles/fpga_miner.dir/build.make CMakeFiles/fpga_miner.dir/algo/sph_cubehash.c.i
.PHONY : algo/sph_cubehash.c.i

algo/sph_cubehash.s: algo/sph_cubehash.c.s
.PHONY : algo/sph_cubehash.s

# target to generate assembly for a file
algo/sph_cubehash.c.s:
	$(MAKE) -f CMakeFiles/fpga_miner.dir/build.make CMakeFiles/fpga_miner.dir/algo/sph_cubehash.c.s
.PHONY : algo/sph_cubehash.c.s

algo/sph_groestl.o: algo/sph_groestl.c.o
.PHONY : algo/sph_groestl.o

# target to build an object file
algo/sph_groestl.c.o:
	$(MAKE) -f CMakeFiles/fpga_miner.dir/build.make CMakeFiles/fpga_miner.dir/algo/sph_groestl.c.o
.PHONY : algo/sph_groestl.c.o

algo/sph_groestl.i: algo/sph_groestl.c.i
.PHONY : algo/sph_groestl.i

# target to preprocess a source file
algo/sph_groestl.c.i:
	$(MAKE) -f CMakeFiles/fpga_miner.dir/build.make CMakeFiles/fpga_miner.dir/algo/sph_groestl.c.i
.PHONY : algo/sph_groestl.c.i

algo/sph_groestl.s: algo/sph_groestl.c.s
.PHONY : algo/sph_groestl.s

# target to generate assembly for a file
algo/sph_groestl.c.s:
	$(MAKE) -f CMakeFiles/fpga_miner.dir/build.make CMakeFiles/fpga_miner.dir/algo/sph_groestl.c.s
.PHONY : algo/sph_groestl.c.s

algo/sph_jh.o: algo/sph_jh.c.o
.PHONY : algo/sph_jh.o

# target to build an object file
algo/sph_jh.c.o:
	$(MAKE) -f CMakeFiles/fpga_miner.dir/build.make CMakeFiles/fpga_miner.dir/algo/sph_jh.c.o
.PHONY : algo/sph_jh.c.o

algo/sph_jh.i: algo/sph_jh.c.i
.PHONY : algo/sph_jh.i

# target to preprocess a source file
algo/sph_jh.c.i:
	$(MAKE) -f CMakeFiles/fpga_miner.dir/build.make CMakeFiles/fpga_miner.dir/algo/sph_jh.c.i
.PHONY : algo/sph_jh.c.i

algo/sph_jh.s: algo/sph_jh.c.s
.PHONY : algo/sph_jh.s

# target to generate assembly for a file
algo/sph_jh.c.s:
	$(MAKE) -f CMakeFiles/fpga_miner.dir/build.make CMakeFiles/fpga_miner.dir/algo/sph_jh.c.s
.PHONY : algo/sph_jh.c.s

algo/sph_keccak.o: algo/sph_keccak.c.o
.PHONY : algo/sph_keccak.o

# target to build an object file
algo/sph_keccak.c.o:
	$(MAKE) -f CMakeFiles/fpga_miner.dir/build.make CMakeFiles/fpga_miner.dir/algo/sph_keccak.c.o
.PHONY : algo/sph_keccak.c.o

algo/sph_keccak.i: algo/sph_keccak.c.i
.PHONY : algo/sph_keccak.i

# target to preprocess a source file
algo/sph_keccak.c.i:
	$(MAKE) -f CMakeFiles/fpga_miner.dir/build.make CMakeFiles/fpga_miner.dir/algo/sph_keccak.c.i
.PHONY : algo/sph_keccak.c.i

algo/sph_keccak.s: algo/sph_keccak.c.s
.PHONY : algo/sph_keccak.s

# target to generate assembly for a file
algo/sph_keccak.c.s:
	$(MAKE) -f CMakeFiles/fpga_miner.dir/build.make CMakeFiles/fpga_miner.dir/algo/sph_keccak.c.s
.PHONY : algo/sph_keccak.c.s

algo/sph_skein.o: algo/sph_skein.c.o
.PHONY : algo/sph_skein.o

# target to build an object file
algo/sph_skein.c.o:
	$(MAKE) -f CMakeFiles/fpga_miner.dir/build.make CMakeFiles/fpga_miner.dir/algo/sph_skein.c.o
.PHONY : algo/sph_skein.c.o

algo/sph_skein.i: algo/sph_skein.c.i
.PHONY : algo/sph_skein.i

# target to preprocess a source file
algo/sph_skein.c.i:
	$(MAKE) -f CMakeFiles/fpga_miner.dir/build.make CMakeFiles/fpga_miner.dir/algo/sph_skein.c.i
.PHONY : algo/sph_skein.c.i

algo/sph_skein.s: algo/sph_skein.c.s
.PHONY : algo/sph_skein.s

# target to generate assembly for a file
algo/sph_skein.c.s:
	$(MAKE) -f CMakeFiles/fpga_miner.dir/build.make CMakeFiles/fpga_miner.dir/algo/sph_skein.c.s
.PHONY : algo/sph_skein.c.s

algo/sponge.o: algo/sponge.c.o
.PHONY : algo/sponge.o

# target to build an object file
algo/sponge.c.o:
	$(MAKE) -f CMakeFiles/fpga_miner.dir/build.make CMakeFiles/fpga_miner.dir/algo/sponge.c.o
.PHONY : algo/sponge.c.o

algo/sponge.i: algo/sponge.c.i
.PHONY : algo/sponge.i

# target to preprocess a source file
algo/sponge.c.i:
	$(MAKE) -f CMakeFiles/fpga_miner.dir/build.make CMakeFiles/fpga_miner.dir/algo/sponge.c.i
.PHONY : algo/sponge.c.i

algo/sponge.s: algo/sponge.c.s
.PHONY : algo/sponge.s

# target to generate assembly for a file
algo/sponge.c.s:
	$(MAKE) -f CMakeFiles/fpga_miner.dir/build.make CMakeFiles/fpga_miner.dir/algo/sponge.c.s
.PHONY : algo/sponge.c.s

api.o: api.c.o
.PHONY : api.o

# target to build an object file
api.c.o:
	$(MAKE) -f CMakeFiles/fpga_miner.dir/build.make CMakeFiles/fpga_miner.dir/api.c.o
.PHONY : api.c.o

api.i: api.c.i
.PHONY : api.i

# target to preprocess a source file
api.c.i:
	$(MAKE) -f CMakeFiles/fpga_miner.dir/build.make CMakeFiles/fpga_miner.dir/api.c.i
.PHONY : api.c.i

api.s: api.c.s
.PHONY : api.s

# target to generate assembly for a file
api.c.s:
	$(MAKE) -f CMakeFiles/fpga_miner.dir/build.make CMakeFiles/fpga_miner.dir/api.c.s
.PHONY : api.c.s

fpga-miner.o: fpga-miner.c.o
.PHONY : fpga-miner.o

# target to build an object file
fpga-miner.c.o:
	$(MAKE) -f CMakeFiles/fpga_miner.dir/build.make CMakeFiles/fpga_miner.dir/fpga-miner.c.o
.PHONY : fpga-miner.c.o

fpga-miner.i: fpga-miner.c.i
.PHONY : fpga-miner.i

# target to preprocess a source file
fpga-miner.c.i:
	$(MAKE) -f CMakeFiles/fpga_miner.dir/build.make CMakeFiles/fpga_miner.dir/fpga-miner.c.i
.PHONY : fpga-miner.c.i

fpga-miner.s: fpga-miner.c.s
.PHONY : fpga-miner.s

# target to generate assembly for a file
fpga-miner.c.s:
	$(MAKE) -f CMakeFiles/fpga_miner.dir/build.make CMakeFiles/fpga_miner.dir/fpga-miner.c.s
.PHONY : fpga-miner.c.s

fpgautils.o: fpgautils.c.o
.PHONY : fpgautils.o

# target to build an object file
fpgautils.c.o:
	$(MAKE) -f CMakeFiles/fpga_miner.dir/build.make CMakeFiles/fpga_miner.dir/fpgautils.c.o
.PHONY : fpgautils.c.o

fpgautils.i: fpgautils.c.i
.PHONY : fpgautils.i

# target to preprocess a source file
fpgautils.c.i:
	$(MAKE) -f CMakeFiles/fpga_miner.dir/build.make CMakeFiles/fpga_miner.dir/fpgautils.c.i
.PHONY : fpgautils.c.i

fpgautils.s: fpgautils.c.s
.PHONY : fpgautils.s

# target to generate assembly for a file
fpgautils.c.s:
	$(MAKE) -f CMakeFiles/fpga_miner.dir/build.make CMakeFiles/fpga_miner.dir/fpgautils.c.s
.PHONY : fpgautils.c.s

libztex.o: libztex.c.o
.PHONY : libztex.o

# target to build an object file
libztex.c.o:
	$(MAKE) -f CMakeFiles/fpga_miner.dir/build.make CMakeFiles/fpga_miner.dir/libztex.c.o
.PHONY : libztex.c.o

libztex.i: libztex.c.i
.PHONY : libztex.i

# target to preprocess a source file
libztex.c.i:
	$(MAKE) -f CMakeFiles/fpga_miner.dir/build.make CMakeFiles/fpga_miner.dir/libztex.c.i
.PHONY : libztex.c.i

libztex.s: libztex.c.s
.PHONY : libztex.s

# target to generate assembly for a file
libztex.c.s:
	$(MAKE) -f CMakeFiles/fpga_miner.dir/build.make CMakeFiles/fpga_miner.dir/libztex.c.s
.PHONY : libztex.c.s

util.o: util.c.o
.PHONY : util.o

# target to build an object file
util.c.o:
	$(MAKE) -f CMakeFiles/fpga_miner.dir/build.make CMakeFiles/fpga_miner.dir/util.c.o
.PHONY : util.c.o

util.i: util.c.i
.PHONY : util.i

# target to preprocess a source file
util.c.i:
	$(MAKE) -f CMakeFiles/fpga_miner.dir/build.make CMakeFiles/fpga_miner.dir/util.c.i
.PHONY : util.c.i

util.s: util.c.s
.PHONY : util.s

# target to generate assembly for a file
util.c.s:
	$(MAKE) -f CMakeFiles/fpga_miner.dir/build.make CMakeFiles/fpga_miner.dir/util.c.s
.PHONY : util.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... fpga_miner"
	@echo "... rebuild_cache"
	@echo "... jansson"
	@echo "... algo/blake256-8.o"
	@echo "... algo/blake256-8.i"
	@echo "... algo/blake256-8.s"
	@echo "... algo/blake2s.o"
	@echo "... algo/blake2s.i"
	@echo "... algo/blake2s.s"
	@echo "... algo/groestl.o"
	@echo "... algo/groestl.i"
	@echo "... algo/groestl.s"
	@echo "... algo/keccak256.o"
	@echo "... algo/keccak256.i"
	@echo "... algo/keccak256.s"
	@echo "... algo/keccak512.o"
	@echo "... algo/keccak512.i"
	@echo "... algo/keccak512.s"
	@echo "... algo/lyra2.o"
	@echo "... algo/lyra2.i"
	@echo "... algo/lyra2.s"
	@echo "... algo/lyra2re.o"
	@echo "... algo/lyra2re.i"
	@echo "... algo/lyra2re.s"
	@echo "... algo/myr-groestl.o"
	@echo "... algo/myr-groestl.i"
	@echo "... algo/myr-groestl.s"
	@echo "... algo/nist5.o"
	@echo "... algo/nist5.i"
	@echo "... algo/nist5.s"
	@echo "... algo/sha2.o"
	@echo "... algo/sha2.i"
	@echo "... algo/sha2.s"
	@echo "... algo/sph_blake.o"
	@echo "... algo/sph_blake.i"
	@echo "... algo/sph_blake.s"
	@echo "... algo/sph_blake2s.o"
	@echo "... algo/sph_blake2s.i"
	@echo "... algo/sph_blake2s.s"
	@echo "... algo/sph_bmw.o"
	@echo "... algo/sph_bmw.i"
	@echo "... algo/sph_bmw.s"
	@echo "... algo/sph_cubehash.o"
	@echo "... algo/sph_cubehash.i"
	@echo "... algo/sph_cubehash.s"
	@echo "... algo/sph_groestl.o"
	@echo "... algo/sph_groestl.i"
	@echo "... algo/sph_groestl.s"
	@echo "... algo/sph_jh.o"
	@echo "... algo/sph_jh.i"
	@echo "... algo/sph_jh.s"
	@echo "... algo/sph_keccak.o"
	@echo "... algo/sph_keccak.i"
	@echo "... algo/sph_keccak.s"
	@echo "... algo/sph_skein.o"
	@echo "... algo/sph_skein.i"
	@echo "... algo/sph_skein.s"
	@echo "... algo/sponge.o"
	@echo "... algo/sponge.i"
	@echo "... algo/sponge.s"
	@echo "... api.o"
	@echo "... api.i"
	@echo "... api.s"
	@echo "... fpga-miner.o"
	@echo "... fpga-miner.i"
	@echo "... fpga-miner.s"
	@echo "... fpgautils.o"
	@echo "... fpgautils.i"
	@echo "... fpgautils.s"
	@echo "... libztex.o"
	@echo "... libztex.i"
	@echo "... libztex.s"
	@echo "... util.o"
	@echo "... util.i"
	@echo "... util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

